name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'TalatCikikci-TomTom'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approved the automated PR"